[en]
grade-table-queston = "Question"
grade-table-total = "Total"
grade-table-points = "Points"
grade-table-grade = "Grade"
point = "point"
points = "points"
page = "Page"
page-counter-display = "1 of 1"
family-name = "Surname"
given-name = "Name"
group = "Group"
date = "Date"
draft-label = "Draft"

[zh]
grade-table-queston = "问题"
grade-table-total = "总分"
grade-table-points = "分数"
grade-table-grade = "等级"
point = "分"
points = "分"
page = "页"
page-counter-display = "第 1 页 共 1 页"
family-name = "姓"
given-name = "名"
group = "组"
date = "日期"